name: vidmaster
description: All-in-One Video & Music Player
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter

  # 🔥 Video Engine
  media_kit: ^1.2.0
  media_kit_video: ^2.0.1
  wakelock_plus: ^1.2.8
  ffmpeg_kit_flutter_full_gpl: 6.0.2

  # 🔊 Audio Engine
  just_audio: ^0.9.46
  audio_service: ^0.18.15
  on_audio_query: ^2.9.0
  flutter_chrome_cast: ^1.2.6

  # ⬇️ Downloader
  flutter_downloader: ^1.11.9
  dio: ^5.7.0
  youtube_explode_dart: ^3.0.5

  # 🧠 State Management
  flutter_riverpod: ^2.6.1
  dartz: ^0.10.1
  fpdart: ^1.1.0

  # 🗄️ Database
  isar_community: ^3.3.2
  isar_community_flutter_libs: ^3.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # 🔐 Security
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.2
  crypto: ^3.0.6
  bcrypt: ^1.1.3

  # 🧭 Navigation
  go_router: ^17.2.3

  # 📁 Files & Permissions
  permission_handler: ^12.0.1
  path_provider: ^2.1.2
  file_picker: ^8.1.7

  # 📤 Sharing
  share_plus: ^10.1.4

  # 🔔 Notifications
  flutter_local_notifications: ^18.0.1

  # 🖼️ Thumbnails
  video_thumbnail: ^0.5.3

  # 🌐 Connectivity
  connectivity_plus: ^6.1.1

  # 🔒 Screen Protection
  flutter_windowmanager: ^0.2.0

  # 💾 Preferences
  shared_preferences: ^2.3.5

  # 🧰 Utils
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  photo_manager: ^3.9.0
  uuid: ^4.5.3
  cached_network_image: ^3.4.1
  super_clipboard: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

  # 🗄️ Isar Generator
  isar_community_generator: ^3.3.2
  build_runner: ^2.4.14

  integration_test:
    sdk: flutter

  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3